window.DVG_I18N = {
  ca: {
    navBook: 'El llibre', navFormats: 'Formats', navReader: 'Lector',
    heroEyebrow: 'Guia oberta · data.europa.eu', byline: 'Publications Office of the European Union<br>i Maarten Lambrechts', discoverBook: 'Descobreix el llibre',
    coverNote: 'Una edició lineal, accessible i preparada per a lectura en veu alta.', introEyebrow: 'Introducció', introTitle: 'Dades que es poden<br>veure i entendre.',
    introLead: 'La visualització de dades transforma informació complexa en una experiència clara, útil i memorable.',
    introBody1: '<cite>Data Visualisation Guide</cite> és una guia pràctica i exhaustiva per aprendre a representar dades amb rigor. Reuneix principis de disseny, narrativa, accessibilitat, tipologies de gràfics i eines de treball en un únic recorregut.',
    introBody2: 'Aquesta edició conserva l’estructura, els exemples visuals, les fonts i els crèdits de la guia oficial. Els continguts interactius s’han adaptat perquè també siguin comprensibles en lectura lineal i amb tecnologies de suport.',
    officialSource: 'Consulta la publicació web original:', factContent: 'Contingut', factAreas: '7 àrees temàtiques', factReading: 'Lectura', factWords: '155.000+ paraules', factLicense: 'Llicència',
    formatsEyebrow: 'Una guia, diverses maneres de llegir-la', formatsTitle: 'El format també<br>forma part de l’accés.',
    formatsLead: 'La guia original és una obra extraordinàriament rica, concebuda com una experiència web extensa i interconnectada.',
    formatsBody1: 'Aquesta arquitectura permet explorar els continguts amb molta llibertat. Alhora, quan es busca una lectura continuada, prendre notes, escoltar el text o consultar-lo sense connexió, la navegació entre moltes pàgines i elements interactius pot interrompre el ritme.',
    formatsBody2: 'Amb la voluntat de facilitar nous contextos de lectura —i amb el màxim respecte pel treball original— oferim aquesta important guia en diversos formats complementaris. No substitueixen l’experiència oficial: l’acompanyen i n’amplien l’accessibilitat.',
    editorNote: '<strong>Jaume Nualart Vilaplana</strong>, expert en visualització de dades, ha preparat i publicat aquestes versions per facilitar l’accés a la publicació i millorar-ne especialment l’accessibilitat visual.',
    licenseText: 'El contingut editorial es comparteix d’acord amb la llicència <a href="https://creativecommons.org/licenses/by/4.0/deed.ca" target="_blank" rel="noreferrer">Creative Commons Reconeixement 4.0 Internacional (CC BY 4.0)</a>. L’autoria correspon a la Publications Office of the European Union i Maarten Lambrechts. Els materials de tercers conserven els crèdits i les condicions indicades a l’obra original.',
    epubDesc: 'Lectura adaptable amb àudio sincronitzat', epubMeta: '1,4 GB · multimèdia', openAudioReader: 'Obre text + àudio', downloadEpub: 'Descarrega EPUB', pdfDesc: 'Maquetació A4 per llegir, anotar o imprimir', pdfMeta: '926 pàgines · 344 MB', mdDesc: 'Text estructurat i editable amb imatges', mdMeta: 'Format obert · 1,2 MB', plainText: 'Text pla', txtDesc: 'Versió lleugera per cercar i escoltar',
    readerEyebrow: 'Lector web', readerTitle: 'Llegeix i escolta aquí,<br>al teu ritme.', readerIntro: 'Escolta l’audiollibre capítol a capítol mentre el text se sincronitza i es ressalta frase a frase.', audioTab: 'Text + Àudio', chapter: 'Capítol', speed: 'Velocitat', previousChapter: '← Capítol anterior', nextChapter: 'Capítol següent →',
    accessibleEdition: 'Edició accessible: Jaume Nualart Vilaplana', loadingBook: 'Carregant el llibre…', fullText: 'Versió completa en text pla · 157.000 paraules aproximadament', searchMatches: '{count} coincidències per a “{query}”', readerLocalError: 'Per activar el lector, obre aquesta pàgina mitjançant un servidor web local.', txtDownload: 'La versió TXT es pot descarregar des de la secció de formats.', audioLoading: 'Carregant l’edició sincronitzada…', audioError: 'No s’ha pogut carregar l’edició àudio + text.'
  },
  en: {
    navBook: 'The book', navFormats: 'Formats', navReader: 'Reader',
    heroEyebrow: 'Open guide · data.europa.eu', byline: 'Publications Office of the European Union<br>and Maarten Lambrechts', discoverBook: 'Discover the book',
    coverNote: 'A linear, accessible edition prepared for read-aloud use.', introEyebrow: 'Introduction', introTitle: 'Data that can be<br>seen and understood.',
    introLead: 'Data visualisation turns complex information into a clear, useful and memorable experience.',
    introBody1: '<cite>Data Visualisation Guide</cite> is a practical and comprehensive guide to representing data rigorously. It brings together design principles, storytelling, accessibility, chart types and working tools in a single journey.',
    introBody2: 'This edition preserves the structure, visual examples, sources and credits of the official guide. Interactive content has been adapted so it remains understandable in linear reading and with assistive technologies.',
    officialSource: 'Visit the original web publication:', factContent: 'Content', factAreas: '7 subject areas', factReading: 'Reading', factWords: '155,000+ words', factLicense: 'Licence',
    formatsEyebrow: 'One guide, several ways to read it', formatsTitle: 'Format is also<br>part of access.',
    formatsLead: 'The original guide is an extraordinarily rich work, conceived as an extensive and interconnected web experience.',
    formatsBody1: 'This architecture offers great freedom to explore the content. At the same time, when readers want a continuous reading experience, to take notes, listen to the text or consult it offline, navigating many pages and interactive elements can interrupt the reading flow.',
    formatsBody2: 'To support new reading contexts—and with the utmost respect for the original work—we offer this important guide in several complementary formats. They do not replace the official experience: they accompany it and broaden its accessibility.',
    editorNote: '<strong>Jaume Nualart Vilaplana</strong>, a data visualisation expert, has prepared and published these versions to facilitate access to the publication and improve its visual accessibility in particular.',
    licenseText: 'The editorial content is shared under the <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noreferrer">Creative Commons Attribution 4.0 International licence (CC BY 4.0)</a>. Authorship belongs to the Publications Office of the European Union and Maarten Lambrechts. Third-party materials retain the credits and conditions stated in the original work.',
    epubDesc: 'Adaptable reading with synchronised audio', epubMeta: '1.4 GB · multimedia', openAudioReader: 'Open text + audio', downloadEpub: 'Download EPUB', pdfDesc: 'A4 layout for reading, annotating or printing', pdfMeta: '926 pages · 344 MB', mdDesc: 'Structured, editable text with images', mdMeta: 'Open format · 1.2 MB', plainText: 'Plain text', txtDesc: 'Lightweight version for searching and listening',
    readerEyebrow: 'Web reader', readerTitle: 'Read and listen here,<br>at your own pace.', readerIntro: 'Listen to the audiobook chapter by chapter while the text is synchronised and highlighted sentence by sentence.', audioTab: 'Text + Audio', chapter: 'Chapter', speed: 'Speed', previousChapter: '← Previous chapter', nextChapter: 'Next chapter →',
    accessibleEdition: 'Accessible edition: Jaume Nualart Vilaplana', loadingBook: 'Loading the book…', fullText: 'Complete plain-text edition · approximately 157,000 words', searchMatches: '{count} matches for “{query}”', readerLocalError: 'To activate the reader, open this page through a local web server.', txtDownload: 'The TXT edition can be downloaded from the formats section.', audioLoading: 'Loading the synchronised edition…', audioError: 'The audio + text edition could not be loaded.'
  }
};
